### ISSUE TITLE
Infografia Gestion de Proyectos de Software

### ISSUE THREAD

**Issue by Joel343** [SistemasTecTlaxiaco/infografia-Joel343-1#2]
![Gestion de Proyectos de Software](https://user-images.githubusercontent.com/79877626/132906916-237034a6-30cd-47aa-a7b1-4f946c53878d.jpg)

**Comment by MarcosJonathan17** [comment]
Da ideas claras y concisas, la información esta bien detallada. Utiliza un diseño muy agradable, utiliza colores, ilustraciones y tipografía muy atractiva, el tamaño de la letra es adecuada.
No contiene ninguna falta ortográfica y utiliza mas de 8 ideas centrales.

calificación: 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado, solo falto las metodologías, herramientas
